name: Delete Merged Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete merged branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const branchName = pr.head.ref;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const defaultBranch = context.payload.repository.default_branch;
            
            // デフォルトブランチは削除しない
            if (branchName === defaultBranch) {
              console.log(`Skipping deletion of default branch: ${branchName}`);
              return;
            }
            
            // フォークからの PR の場合はスキップ
            if (pr.head.repo.full_name !== pr.base.repo.full_name) {
              console.log('PR is from a fork, skipping branch deletion');
              return;
            }
            
            // 保護されたブランチかどうかをチェック
            try {
              const protection = await github.rest.repos.getBranchProtection({
                owner: owner,
                repo: repo,
                branch: branchName
              });
              
              if (protection.data) {
                console.log(`Skipping deletion of protected branch: ${branchName}`);
                return;
              }
            } catch (error) {
              // 404エラーは保護されていないことを意味するので続行
              if (error.status !== 404) {
                console.log(`Warning: Could not check protection status for branch ${branchName}:`, error.message);
              }
            }
            
            try {
              await github.rest.git.deleteRef({
                owner: owner,
                repo: repo,
                ref: `heads/${branchName}`
              });
              console.log(`Successfully deleted branch: ${branchName}`);
            } catch (error) {
              console.error(`Failed to delete branch ${branchName}:`, error.message);
              // ブランチが既に削除されている場合はエラーを無視
              if (error.status !== 422) {
                throw error;
              }
            }